import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Header from "../../component/Header/Header.jsx";
import Footer from "../../component/Footer/Footer.jsx";
import DetailImageContainer from "../../component/DetailImageContainer/DetailImageContainer.jsx";
import BackButton from "../../component/BackButton/BackButton.jsx";

export default function Home() {
  return (
    <div className={styles.art}>
      <Head>
        <title>index pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://use.typekit.net/xfh7fer.css"
        ></link>
      </Head>

      <Header />
      <div className={styles.container__box}>
        <main>
          <DetailImageContainer
          // imgA="/08B65F5B-B105-4D6B-88A0-03D642D12AE6.jpeg"
          // imgB="/84E28BF2-E18F-45A7-BDA5-FB5532D24CAB.jpeg"
          // imgC="/F6A9D47B-2052-4786-BD47-C10810B612B0.jpeg"
          />
          <BackButton />
        </main>
      </div>
      <Footer />
    </div>
  );
}
