import Head from "next/head";
// import { useInView } from "react-intersection-observer";

// import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../component/Header/Header.jsx";
import TopMain from "../component/Main/TopMain.jsx";
import Footer from "../component/Footer/Footer.jsx";

export default function Home() {
  // const { ref, inView } = useInView({
  //   rootMargin: "10px",
  //   threshold: [0.5],
  // });
  return (
    <div className={styles.art}>
      <Head>
        <title>index pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://use.typekit.net/xfh7fer.css"
        ></link>
      </Head>

      <Header />
      <div className={styles.container__box}>
        <TopMain />
      </div>
      <Footer />
    </div>
  );
}
